# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: profiles-microservice-consumer
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://104.155.169.205:1111/eureka/
  instance: 
    preferIpAddress: true

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false
